### ISSUE TITLE
SMS send leads to crash in 6.0+

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink-android#11]
On my Nexus 5x running 6.0.1

I attempted to send my order via SMS when I had it in airplane mode and it crashed when I tried to hit OK to send via SMS.

**Comment by choquette33** [comment]
@neerajrao - This works on my Nexus 5s now... should we close it?

**Comment by neerajrao** [comment]
@choquette33 yup. Closing. Thanks for the confirmation.
